<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Prestacol.Domain\Prestacol.Domain.csproj" />
    <ProjectReference Include="..\PrestaColombia.Domain\PrestaColombia.Domain.csproj" />
  </ItemGroup>

</Project>
